anvilresearch/connect

- lib/oidc/token.js
token.expires_in was undefined so ID tokens were always deemed expired on the anvil-connect-sdk side
> fix ID Token expiry delta (was undefined so token expired immediately)

- lib/cli/deployment/Dockerfile
- lib/cli/deployment/docker-compose.yml
- lib/cli/deployment/nginx.conf
Initial stages of a few deployment file examples for Docker (& Docker Compose) behind an nginx proxy.
Let me know if you see any need for updates at this point.
> Deployment

- oidc/error.js
The `func(statusCode, messageBody)` pattern has been deprecated in favour of `status(statusCode).func(messageBody)`
> Update to match express v4 API

- providers/index.js
Allows provider templates to be created, which define properties which can then
be inherited by multiple providers.
**Template**:
```js
module.exports = function(config, templateConfig) {
return {
id: 'ActiveDirectory',
protocol: 'ActiveDirectory',
mapping: {
id:          'objectGUID',
email:       'userPrincipalName',
name:        'name',
givenName:   'givenName',
familyName:  'sn',
phoneNumber: function (info) {
return info.telephoneNumber ||
info.mobile ||
info.homePhone ||
info.otherHomePhone ||
info.otherTelephone ||
info.ipPhone ||
info.otherIpPhone;
}
}
};
};
```
**Inheriting provider**:
```js
module.exports = function(config) {
return {
id: 'mycorpad',
name: 'Umbrella Corp',
templates: [ 'ActiveDirectory' ]
};
};
```
> Add provider templating for boot-time inheritance

- routes/connect.js
Fixes issue where the `authenticate` handler may fail when trying to reference `next`, which is undefined unless passed as a parameter.
Example stack trace:
```text
anvil-connect/node_modules/passport/lib/middleware/authenticate.js:336
next(err);
^
TypeError: next is not a function
at OAuthStrategy.strategy.error (anvil-connect/node_modules/passport/lib/middleware/authenticate.js:336:9)
at anvil-connect/protocols/OAuth.js:552:25
at anvil-connect/protocols/OAuth.js:346:14
at Request.callback (anvil-connect/node_modules/superagent/lib/node/index.js:797:3)
at Stream.<anonymous> (anvil-connect/node_modules/superagent/lib/node/index.js:990:12)
at emitNone (events.js:72:20)
at Stream.emit (events.js:166:7)
at Unzip.<anonymous> (anvil-connect/node_modules/superagent/lib/node/utils.js:108:12)
at …
```
> fix(routes): Pass `next` to `passport.authenticate`

- oidc/verifyAuthorizationCode.js
`callback` is not defined in this context. Instead, the correct function to use is `next` (see `verifyAuthorizationCode` parameters)
> Fix callback function name

- boot/keys.js
- boot/redis.js
- boot/server.js
- lib/time-utils.js
- models/Client.js
- models/ClientToken.js
- models/UserApplications.js
- oidc/signout.js
- oidc/verifyClientRegistration.js
- oidc/verifyClientToken.js
- protocols/OAuth.js
- protocols/OpenID.js
- providers/mailchimp.js
- routes/authorizations.js
- routes/register.js
- routes/signin.js
- routes/userinfo.js
- server.js
- test/oidc/signout.coffee
Pardon me if the commit messages aren't quite what they should be; I'm not yet accustomed to the style yet. Please let me know if anything is off kilter.
Test results:
```text
1018 passing (3s)
33 pending
1 failing
1) Verify Scoped Client Registration with sufficient scope should not provide an error:
AssertionError: expected { Object (name, error, ...) } to be undefined
```
> Various bugfixes and style adjustments

- README.md
Changed the setup instructions for clarity; fixed some minor content and style issues
> Clarified setup instructions

- boot/server.js
Previously, views were loaded exclusively from the project directory. Now views are loaded from the package views directory by default and can be overridden individually from the project views directory, if necessary. This simplifies setup because we don't need to generate views as part of initializing the project.
> Allow views to be overridden individually.

- oidc/index.js
- oidc/setSessionAmr.js
- routes/connect.js
- routes/signin.js
- routes/signup.js
We now set amr values consistently at the signin, signup and connect
endpoints. Empty amr arrays are no longer added to the session.
> fix(oidc): set amr values consistently

- .gitignore
- boot/passport.js
- boot/server.js
- lib/authenticator.js
- oidc/authenticateUser.js
- oidc/checkSession.js
- oidc/requireSignin.js
- oidc/sessionEvents.js
- oidc/signout.js
- package.json
- public/javascript/session.js
- routes/connect.js
- routes/signin.js
- routes/signup.js
- server.js
- test/unit/oidc/authenticateUser.coffee
- test/unit/oidc/requireSignin.coffee
- test/unit/oidc/sessionEvents.coffee
- test/unit/oidc/signout.coffee
Logic in the passport library was conflicting in scope with Anvil Connect's own provider handling.
Now, strategies are interfaced with directly, and there is no need to bring in the passport library itself.
This maintains compatibility with existing passport strategies.
Fixes #143
> Remove passport dependency

- models/Client.js
- test/unit/models/clientSpec.coffee
Fixes #98 
This involved customizing the validation function for the `Client` model because there is no logic in [Modinha](https://github.com/anvilresearch/modinha) or [Revalidator](https://github.com/flatiron/revalidator) that supports cross-property validation rules.
cc @christiansmith
> Validate that jwks and jwks_uri are not used together

- models/Client.js
`value` is the new set of `redirect_uris`, whereas `instance.redirect_uris` is the original set. Validating `instance.redirect_uris` has the effect of validating the existing data instead of the new/incoming data.
> Validate new redirect_uris instead of original values

- oidc/validateAuthorizationParams.js
- oidc/verifyClient.js
- routes/authorize.js
- routes/connect.js
- routes/signin.js
- routes/signup.js
- test/unit/oidc/validateAuthorizationParams.coffee
- test/unit/oidc/verifyClient.coffee
Fixes a security vulnerability where, under certain circumstances, a malicious user can take advantage of any endpoint using `validateAuthorizationParams` to redirect an unsuspecting individual to a malicious website.
**Proof of concept:** https://connect.example.com/signin?redirect_uri=http://malware.com
> Always verify redirect_uri before issuing redirect

- lib/authenticator.js
Prior, if no callback was given, the logic would assume that `options` was the callback. Now, it checks to make sure that `options` is a function first before making that same assumption.
> Fix handling of optional `options` parameter in Passport shim

- models/Client.js
- test/unit/models/clientSpec.coffee
> Trim whitespace around redirect URIs

- boot/server.js
- boot/settings.js
- boot/setup.js
- oidc/requireVerifiedEmail.js
- protocols/Password.js
- routes/setup.js
- routes/signin.js
- server.js
- test/unit/boot/setup.coffee
- test/unit/oidc/requireVerifiedEmail.coffee
- If no users with the `authority` role exist in the database, the server allows the use of a setup REST endpoint to create the first authority user and register the CLI client. A token, saved to the keys directory, is required to prevent the endpoint from being used by an opportunist
- All providers now support a `hidden` boolean property which hides the provider off the sign-in screen
- The password provider can be limited to only authenticate users with a certain role using the `allowRoles` array property on the provider configuration
> Create first time setup endpoint

- README.md
Maintaining all different copies of the getting started guide is becoming an unnecessary burden.
> Link to getting started guide in connect-docs

- CONTRIBUTING.md
The tiny blurb under "Vet" is hidden away at the bottom.
Instead, we need a crystal clear, unmissable section on code style.
> Create separate section for code style guidelines

- boot/mailer.js
Prior, it wouldn't accept `no-reply@example.com` because of the hyphen in `no-reply`. Now, assuming all is well, it should be able to accept any valid e-mail address, provided that e-mail address is encoded out to safe ASCII characters.
> Make from field validation regex more flexible

- models/User.js
A recent commit changed `User.prototype.authorizedScope` to look up unrestricted scopes from the data store. This change wrapped a `this._id` in a new function, causing the references to that property to be undefined. This caused user role lookups to always result in an empty array, and therefore authorization requests including restricted scopes would issue tokens omitting those scopes. This PR fixes the problem.
> Repair broken `this` reference in authorizedScope()

- package.json
PR #268 removes most of the references to the old CLI, but it was still referenced from `package.json`. This removes that reference.
> Remove `nv` binary reference

- views/signin.jade
The signin form was missing a hidden field for the response_mode parameter. Added it to allow caller to specify a response mode. 
Also, made the addition conditional to match the SPEC which indicates to only include the parameter if it varies from the default. If the response_mode is not supplied to the signin form, it is not added to the authorization details.
> Specifying 'query' response_mode still resulted in fragmented (#) response.

- .travis.yml
- README.md
- coverage.sh
- package.json
Add coveralls badge and improve build script.
**Update original comment!**
The introduction of the coveralls build somewhat unintentionally
had all tests running at once. This used to fail which was the reason
that the coverage.sh script was introduced so that the coverage would
run separately for unit and integration tests and the results were combined.
However it should really be possible to run all tests at once, so that
it makes sense to do so in the build. This should allow to see regressions
in this respect.
The coverage script itself is kept as it can still be useful during
development if only to see how one can run the commands in a shell without
installing istanbul or mocha globally.
Finally the travis script now sends coverage data in a second step to
coveralls with the intent …
> Improve coveralls in travis build

- boot/logger.js
If the `logs` folder is not available the server will boot up fine, but crash as soon as a log entry is made.I think it's probably better to crash as soon as possible.
I did use the asynchronous versions of `stat` and `access` here, which may cause server boot to be aborted while it's doing other things. I'm not exactly sure if this could actually happen though nor that if it did whether that'd be harmful.
Any input on that is welcome. I can always switch the logic out of the synchronous versions. I don't think keeping the asynchronous version and only setting up the export when the `logs` folder has been verified would work.
Another solution of course would be to add the `logs` folder to the repository itself, but I'm leaning toward creating it if necessary to keep the repository clear …
> Ensure writable `logs` folder on boot

- routes/rest/v1/clientRoles.js
- server.js
- test/integration/rest/v1/clientRoles.coffee
This is shamelessly duplicated from the `userRoles` code (both the implementation as well as the tests), but I guess that's okay as it pretty much represents the exact same functionality apart from the targeted resource.
Of course the duplication could probably be removed, but I personally like the straightforwardness of defining these roles this way given the amount of duplication.
> Add endpoints for manipulating client roles

- models/Client.js
The `authorizedScope` method should return an array of strings. Before
this fix it would return an array of arrays of strings. This would cause
scopes assigned to clients through roles to not be properly picked up.
> Return array of strings from `authorizedScope`

- boot/logger.js
- lib/fs-utils.js
- test/unit/lib/fs-utils.coffee
This extracts the functionality for ensuring the `logs` folder exists and is writable. Through this extraction the code can be tested, bringing the coverage of the codebase back up over 80%.
The tests may be an overly explicit, so any refactoring suggestions on that are welcome. It's basically my first time using these libraries, so I had to look up most functionality and am not really aware of best practices surrounding them.
> Extract `ensureWritableDirectory` to `fs-utils`

- boot/settings.js
- models/AccessToken.js
- test/unit/models/accessTokenSpec.coffee
Hello,
In the current implementation, we can call the /token with refresh_token grant type only once...
The new token instance doesn't contains a refresh_token, is it on purpose ?
If not may this PR solve this issue :-)
Regards,
Camille
> provide a new refresh_token with token after refresh

- package.json
This only adds `NODE_ENV=test` for test scripts in package.json so that
$ git clone $anvil_connect_uri && cd connect && npm install && npm test
works!
> Make npm test work out of the box.

- oidc/signout.js
- test/unit/oidc/signout.coffee
it enable the same possibility as the state param in authorize query param, to give the client the possibility to keep a state and retrieve it after logout
> feat(state param signout): add state param for signout redirect like authorize

- views/authorize.jade
For implicit auth requests with non-trusted clients, users are presented with the Authorization / consent screen. The `response_mode` hidden field was missing on the template, so the response mode defaulted to `fragment` or whatever. 
This adds the missing field.
> Add response_mode hidden field to authorize view

- oidc/requireVerifiedEmail.js
In some cases, I was getting a `null` value back for a `role` returned in the `listByUsers` callback.
I am working on figuring out what the issue in the underlying database is, but this guards against it in the event that it occurs.
> fix(oidc): ensure role present and has name attr

- boot/logger.js
Currently a custom logger.js file is expected to be found in the anvil-connect node package root - if a logger.js file is added there it's deleted every time node_modules is reinstalled.
As discussed in the original commit here: https://github.com/anvilresearch/connect/commit/68ba379e4355ae70b36ea2d1a0f1ddf18b90a562 this PR changes the behaviour to look relative to where anvil is being run from.
> fix(logger) default logger.js location

- oidc/requireSignin.js
Hello
> OAuth 2.0 state value REQUIRED if the Authorization Request included the state parameter.
[3.1.2.6.  Authentication Error Response](http://openid.net/specs/openid-connect-core-1_0.html#AuthError)
[3.2.2.6.  Authentication Error Response](http://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthError)
> add a state parameter to authentication error response

- package.json
The latest version of express-bunyan-logger includes the option to obfuscate specific fields based on patterns. 
This is really useful if you want to hide the body.password field which is currently logged by for failed signin attempts. Often users type their email in incorrectly but their password correctly so their valid password will be left hanging around in log files.
Will update docs with example of obfuscating as well.
> Bump express-bunyan-logger
